### PR TITLE
Authorization code-review

### PR DESCRIPTION
**Pull request by Kevin-K**
The authorization code is at a review point. 

I expect the request's put in place to need some modification, especially the `connect` request.

Bullet points of key review points to follow.

### CODE REVIEW

**Comment by Kevin-K** [comment]
## Attributes used thus far
* __ozp:iwc:origin__ - [assigned to a PostMessageParticipant on creation](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-6e2ce11623581daa893742380ecc4a78R56)
* __ozp:iwc:address__ - [assigned to a participant when connecting to a router](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-c9486b4bf61fa319270f201b4c83f44dR42)
* __ozp:iwc:sendAs__ - [assigned to a participant when connecting to a router](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-c9486b4bf61fa319270f201b4c83f44dR42) [ and when joining a multicast group](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-c2241c54c7ba7128f77ca31e769a077aR382)
* __ozp:iwc:receiveAs__ - [assigned to a participant when connecting to a router](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-c9486b4bf61fa319270f201b4c83f44dR42)[ and when joining a multicast group](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-c2241c54c7ba7128f77ca31e769a077aR382)

**Comment by Kevin-K** [comment]
## Policies thus far
* [__/policy/connect__](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-0a5a3708978e6c0a4e46808a7fbfd07bR11)
    * __Enforces__ : Only approved domains can connect to the IWC bus implementation. In current state only localhost and github.io are whitelisted. 
    * __Usage__ : [When a PostMessageParticipant receives a message from an unknown participant it attempts to allow it to connect](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-516c87d2e5b4ba505732f3ca3862e451R245)
* [__/policy/sendAs__](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-0a5a3708978e6c0a4e46808a7fbfd07bR46)  
    * __Enforces__ : Only approved participants can transmit packets as a given source address.
    * __Usage__ : [When a Participant wants to send a packet](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-989948cf469ca5e2c3ab69053ba2636bR237)
* [__/policy/receiveAs__](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-0a5a3708978e6c0a4e46808a7fbfd07bR58)
    * __Enforces__ : Only approved participants can receive packets as a given destination address.
    * __Usage__ : [When a Participant wants to receive a packet from a router](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-989948cf469ca5e2c3ab69053ba2636bR119)
* [__/policy/read__](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-0a5a3708978e6c0a4e46808a7fbfd07bR70) 
    * __Enforces__ : A participant can only read a packets content if it has the security attributes to do so.
    * __Usage__ : [When a Participant wants to read a packet received from a router](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-989948cf469ca5e2c3ab69053ba2636bR137)
* [__/policy/apiNode__](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-0a5a3708978e6c0a4e46808a7fbfd07bR82)
    * __Enforces__ : An api node can be viewed/modified/created only if it has the security attributes to match the requesting packet.
    * __Usage__ : [When handling an api request](https://github.com/ozone-development/ozp-iwc/pull/207/files#diff-41de19087b1807c2baeb564340966357R374)

**Comment by nialscorva** [comment]
Merge this once the following are addressed:
* In `defaultPolicies`, change the policy names to the form: `policy://ozpIwc/{name}`
  * E.g. `/policy/connect` -> `policy://ozpIwc/connect`

Restructure the security tree a bit:
* remove `basicAuthentication.js` and `basicAuthorization.js` since they are not used.
* remove the 'pbac' and 'points' directories (move the contents up one directory)
* move `combining` into policies
*  Merge `abacPolicies.js` and `defaultPolicies.js` into `ozpIwcPolicies.js`.
  * Looks like half of `abacPolicies.js` is unused (`permitWhenObjectHasNoAttributes`, `subjectHasAllObjectAttributes`, and `implies`). The other half is only used by `defaultPolicies.js`.  

After the changes, the tree should look like:
  * `app/js/bus/security/`
    * `elements/securityAttribute.js`
    * `policies/ozpIwcPolicies.js`
    * `policies/policyCombining.js`
    * `pdp.js`
    * `prp.js`
    * `pip.js`

This is already a monster merge, so the rest of the changes will go into future tickets.

**Comment by Kevin-K** [comment]
With the merge of `abacPolicies` and `defaultPolicies` policies into `ozpIwcPolicies` the unused utility functions for policies you mentioned were kept. They didn't serve a purpose in the initial policies but for the time being they may come of use as we move into v0.3

**Pull request merged**
